### PR TITLE
let createPluginsClasspath scan for jars in plugin/plugin/lib

### PR DESCRIPTION
**Pull request by danielwegener**
Some plugins (e.g. cucumber-java) put their own plugin name as directory into the zip. This pr adds scanning for jars in those plugins.

### CODE REVIEW

**Comment by nkly** [comment]
Hi! Thanks for the PR. I've solved this problem before with [this method](https://github.com/dancingrobot84/sbt-idea-plugin/blob/master/src/main/scala/Tasks.scala#L72), but it seems that I've missed the case where there is more than one directory in archive. 

While I think your solution is good, it restricts name of a plugin to be exactly the same as the name of its directory in archive. Sometimes it's hard to predict what name is in archive without downloading it (for example, could you guess the name of the directory of [this plugin](https://plugins.jetbrains.com/plugin/6834?pr=idea)). Taking this into consideration, I can not accept your PR

**Comment by danielwegener** [comment]
Hi there! No problems - but would there be anything against to just add all jar files from a plugins extracted folder to the classpath?

**Comment by nkly** [comment]
Yes, there would. I'll just change existing algorithm slightly: it will search for directories with `lib` subdirectory and add jars from them. I'll fix it ASAP.

**Comment by danielwegener** [comment]
Cool, cheers!

**Pull request closed without merging**
